version: '3'

services:
  offer-db: # Postgresql database for offers
    image: offer-db:latest
    container_name: offer-db
    volumes:
      - offer-db_data:/var/lib/postgresql/data
    networks:
      - offer-network
    environment:
      POSTGRES_USER: seasonsforce
      POSTGRES_PASSWORD: seasonsforce
      POSTGRES_DB: offer
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U seasonsforce -d offer"]
      interval: 30s
      timeout: 60s
      retries: 5

  offer-api:
    image: offer-api:latest  # Spring Boot API for offers
    container_name: offer-api
    depends_on:
      offer-db:
        condition:
          service_healthy
      keycloak-server:
        condition:
          service_healthy
      discovery-service:
        condition:
          service_healthy
      config-server:
        condition:
          service_healthy
    networks:
      - offer-network
      - api-network
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 15

  address-db: # Postgresql database for addresses
    image: address-db:latest
    container_name: address-db
    volumes:
      - address-db_data:/var/lib/postgresql/data
    networks:
      - address-network
    environment:
      POSTGRES_USER: seasonsforce
      POSTGRES_PASSWORD: seasonsforce
      POSTGRES_DB: address
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U seasonsforce -d address"]
      interval: 30s
      timeout: 60s
      retries: 5

  address-api:
    image: address-api:latest  # Spring Boot API for addresses
    container_name: address-api
    depends_on:
      address-db:
        condition:
          service_healthy
      keycloak-server:
        condition:
          service_healthy
      discovery-service:
        condition:
          service_healthy
      config-server:
        condition:
          service_healthy
    networks:
      - address-network
      - api-network
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 15

  company-db: # Postgresql database for companies
    image: company-db:latest
    container_name: company-db
    volumes:
      - company-db_data:/var/lib/postgresql/data
    networks:
      - company-network
    environment:
      POSTGRES_USER: seasonsforce
      POSTGRES_PASSWORD: seasonsforce
      POSTGRES_DB: company
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U seasonsforce -d company"]
      interval: 30s
      timeout: 60s
      retries: 5

  company-minio: # Minio database for companies
    image: company-minio:latest
    container_name: company-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - company-minio-data:/data
    networks:
      - company-network
      - api-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 10s
      retries: 15

  company-api:
    image: company-api:latest  # Spring Boot API for companies
    container_name: company-api
    depends_on:
      company-db:
        condition:
          service_healthy
      company-minio:
        condition:
          service_healthy
      keycloak-server:
        condition:
          service_healthy
      discovery-service:
        condition:
          service_healthy
      config-server:
        condition:
          service_healthy
    networks:
      - company-network
      - api-network
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 15

  api-gateway:
      image: api-gateway:latest  # Spring API Gateway
      container_name: api-gateway
      depends_on:
        config-server:
            condition:
                service_healthy
        discovery-service:
            condition:
                service_healthy
      ports:
        - "8090:8080"  # Output to port 8090
      networks:
        - api-network
      healthcheck:
        test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
        interval: 20s
        timeout: 5s
        retries: 15

  discovery-service:
      image: discovery-service:latest  # Discovery server Eureka
      container_name: discovery-service
      depends_on:
        config-server:
          condition:
            service_healthy
      ports:
          - "8761:8761"  # Output to port 8761
      networks:
        - api-network
      healthcheck:
        test: "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
        interval: 20s
        timeout: 5s
        retries: 15

  config-server:
    image: config-server:latest  # Spring Cloud Config Server
    container_name: config-server
    ports:
        - "4300:8888"  # Output to port 4300
    networks:
      - api-network
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 50

  keycloak-server:
    image: keycloak-server:latest
    hostname: keycloak-server
    container_name: keycloak-server
    ports:
      - ${KEYCLOAK_PORT}
    build: .
    depends_on:
        keycloak-db:
            condition:
                service_healthy
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB_URL_HOST: ${KC_DB_URL_HOST}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB: ${KC_DB}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_HEALTH_ENABLED: ${KC_HEALTH_ENABLED}
    healthcheck:
        test: [ "CMD-SHELL", "bash -c 'echo -n > /dev/tcp/0.0.0.0/8080'"]
        interval: 10s
        retries: 30
        timeout: 5s
    networks:
        - keycloak-network
        - api-network

  keycloak-db:
    image: keycloak-db:latest
    hostname: keycloak-db
    container_name: keycloak-db
    volumes:
        - keycloak-db_data:/var/lib/postgresql/data
    ports:
      - ${KC_POSTGRES_PORT}
    networks:
        - keycloak-network
    environment:
      POSTGRES_DB: ${KC_POSTGRES_DB}
      POSTGRES_USER: ${KC_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KC_POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 30s
      timeout: 60s
      retries: 5

networks:
  offer-network:
  address-network:
  company-network:
  api-network:
  keycloak-network:

volumes:
  offer-db_data:
  address-db_data:
  company-db_data:
  keycloak-db_data:
  company-minio-data: