version: '3'

services:
  offer-db: # Postgresql database for offers
    image: offer-db:latest
    container_name: offer-db
    volumes:
      - offer-db_data:/var/lib/postgresql/data
    networks:
      - offer-network

  offer-api:
    image: offer-api:latest  # Spring Boot API for offers
    container_name: offer-api
    depends_on:
      - config-server
      - offer-db
    networks:
      - offer-network
      - api-network

  address-db: # Postgresql database for addresses
    image: address-db:latest
    container_name: address-db
    volumes:
      - address-db_data:/var/lib/postgresql/data
    networks:
      - address-network

  address-api:
    image: address-api:latest  # Spring Boot API for addresses
    container_name: address-api
    depends_on:
      - config-server
      - address-db
    networks:
      - address-network
      - api-network

  company-db: # Postgresql database for companies
    image: company-db:latest
    container_name: company-db
    volumes:
      - company-db_data:/var/lib/postgresql/data
    networks:
      - company-network

  company-api:
    image: company-api:latest  # Spring Boot API for companies
    container_name: company-api
    depends_on:
      - config-server
      - company-db
    networks:
      - company-network
      - api-network

  api-gateway:
      image: api-gateway:latest  # Spring API Gateway
      container_name: api-gateway
      depends_on:
        - config-server
        - offer-api
        - discovery-service
      ports:
        - "8090:8080"  # Output to port 8090
      networks:
        - api-network

  discovery-service:
      image: discovery-service:latest  # Discovery server Eureka
      container_name: discovery-service
      depends_on:
        - config-server
      ports:
          - "8761:8761"  # Output to port 8761
      networks:
        - api-network

  config-server:
    image: config-server:latest  # Spring Cloud Config Server
    container_name: config-server
    ports:
        - "4300:8888"  # Output to port 4300
    networks:
      - api-network

  keycloak:
    image: keycloak-srv:latest
    hostname: keycloak-srv
    ports:
        - "9090:8080"
    build: .
    depends_on:
        - keycloak-db
    networks:
        - keycloak-network
        - api-network

  keycloak-db:
    image: keycloak-db:latest
    hostname: keycloak-db
    volumes:
        - keycloak-db_data:/var/lib/postgresql/data
    networks:
        - keycloak-network

networks:
  offer-network:
  address-network:
  company-network:
  api-network:
  keycloak-network:

volumes:
  offer-db_data:
  address-db_data:
  company-db_data:
  keycloak-db_data: