version: '3'

services:
  offers-db: # Base de données postgresql pour les offres
    image: offers-db:latest
    container_name: offers-db
    depends_on:
      - discovery-service
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - offers-network

  offers-api:
    image: offers-api:latest  # API Spring Boot pour les offres
    container_name: offers-api
    depends_on:
      - offers-db
    networks:
      - offers-network

  api-gateway:
      image: api-gateway:latest  # API Spring Gateway
      container_name: api-gateway
      depends_on:
        - offers-api
      ports:
        - "8090:8080"  # Sortie vers le port 8090
      networks:
        - offers-network

  discovery-service:
      image: discovery-service:latest  # Serveur discovery Eureka
      container_name: discovery-service
#      depends_on:
#          - api-gateway
      ports:
          - "8761:8761"  # Sortie vers le port 8761
      networks:
          - offers-network

networks:
  offers-network:
    driver: bridge

volumes:
  db_data: