version: '3'

services:
  offers-db: # Base de données postgresql pour les offres
    image: offers-db:latest
    container_name: offers-db
    volumes:
      - offers-db_data:/var/lib/postgresql/data
    networks:
      - offers-network

  offers-api:
    image: offers-api:latest  # API Spring Boot pour les offres
    container_name: offers-api
    depends_on:
      - config-server
      - offers-db
    networks:
      - offers-network
      - api-gateway

  address-db: # Base de données postgresql pour les adresses
    image: address-db:latest
    container_name: address-db
    volumes:
      - address-db_data:/var/lib/postgresql/data
    networks:
      - address-network

  address-api:
    image: address-api:latest  # API Spring Boot pour les offres
    container_name: address-api
    depends_on:
      - config-server
      - address-db
    networks:
      - address-network
      - api-gateway

  company-db: # Base de données postgresql pour les adresses
    image: company-db:latest
    container_name: company-db
    volumes:
      - company-db_data:/var/lib/postgresql/data
    networks:
      - company-network

  company-api:
    image: company-api:latest  # API Spring Boot pour les offres
    container_name: company-api
    depends_on:
      - config-server
      - company-db
    networks:
      - company-network
      - api-gateway

  api-gateway:
      image: api-gateway:latest  # API Spring Gateway
      container_name: api-gateway
      depends_on:
        - config-server
        - offers-api
        - discovery-service
      ports:
        - "8090:8080"  # Sortie vers le port 8090
      networks:
        - api-gateway

  discovery-service:
      image: discovery-service:latest  # Serveur discovery Eureka
      container_name: discovery-service
      depends_on:
        - config-server
      ports:
          - "8761:8761"  # Sortie vers le port 8761
      networks:
        - api-gateway

  config-server:
    image: config-server:latest  # Serveur discovery Eureka
    container_name: config-server
    ports:
        - "4300:8888"  # Sortie vers le port 8080
    networks:
      - api-gateway

networks:
  offers-network:
  address-network:
  company-network:
  api-gateway:

volumes:
  offers-db_data:
  address-db_data:
  company-db_data: